global:
  smtp_smarthost: 'localhost:587'
  smtp_from: 'alertmanager@tradingbot.local'

route:
  group_by: ['alertname']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 1h
  receiver: 'trading-bot-alerts'

receivers:
- name: 'trading-bot-alerts'
  email_configs:
  - to: 'admin@tradingbot.local'

inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname']
